---
name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: Install tooling using asdf
        uses: asdf-vm/actions/install@05e0d2ed97b598bfce82fd30daf324ae0c4570e6 # v3
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        name: Validate renovate5.json
        with:
          extra_args: --all-files --verbose
      - name: Prepare for pre-commit
        run: |
          cp default.json5 .github/renovate.json5  # renovate-config-validator hook can only validate files that are called renovate.json5
          git add .github/renovate.json5
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        name: Validate default5.json
        with:
          extra_args: --all-files --verbose
